# SettingsYaml settings file
mysql_user: "fair"
mysql_password: ""
mysql_host: ""
mysql_port: 3306
mysql_database: "fair"
base_url: "http://localhost:8080"
packing_platform_host: "http://localhost:8080"
